#!/usr/bin/env python

from ROOT import *
from array import array

# ROOT general options
gROOT.SetBatch(kTRUE)
gROOT.SetStyle("Plain")
gStyle.SetOptStat("emruo")

file = TFile("METExamplesRECOAOD_output.root")

h_GenMET  = file.Get("metExamplesRECOAOD/h_GenMET")
h_CaloMET = file.Get("metExamplesRECOAOD/h_CaloMET")
h_TCMET   = file.Get("metExamplesRECOAOD/h_TCMET")
h_PFMET   = file.Get("metExamplesRECOAOD/h_PFMET")

h_GenMET.SetTitleOffset(1.25,"Y")
h_GenMET.SetLineWidth(3)
h_GenMET.SetLineColor(kBlack)
statsGenMET = TPaveStats(0.2,0.8,0.4,1.0,"brNDC")
statsGenMET.SetName("stats")
statsGenMET.SetBorderSize(1)
statsGenMET.SetTextAlign(12)
statsGenMET.SetFillColor(0)
statsGenMET.SetLineColor(kBlack)
statsGenMET.SetTextColor(kBlack)
h_GenMET.GetListOfFunctions().Add(statsGenMET)
h_CaloMET.SetLineWidth(3)
h_CaloMET.SetLineColor(kRed)
statsCaloMET = TPaveStats(0.4,0.8,0.6,1.0,"brNDC")
statsCaloMET.SetName("stats")
statsCaloMET.SetBorderSize(1)
statsCaloMET.SetTextAlign(12)
statsCaloMET.SetFillColor(0)
statsCaloMET.SetLineColor(kRed)
statsCaloMET.SetTextColor(kRed)
h_CaloMET.GetListOfFunctions().Add(statsCaloMET)
h_TCMET.SetLineWidth(3)
h_TCMET.SetLineColor(kBlue)
statsTCMET = TPaveStats(0.6,0.8,0.8,1.0,"brNDC")
statsTCMET.SetName("stats")
statsTCMET.SetBorderSize(1)
statsTCMET.SetTextAlign(12)
statsTCMET.SetFillColor(0)
statsTCMET.SetLineColor(kBlue)
statsTCMET.SetTextColor(kBlue)
h_TCMET.GetListOfFunctions().Add(statsTCMET)
h_PFMET.SetLineWidth(3)
h_PFMET.SetLineColor(kGreen+2)
statsPFMET = TPaveStats(0.8,0.8,1.0,1.0,"brNDC")
statsPFMET.SetName("stats")
statsPFMET.SetBorderSize(1)
statsPFMET.SetTextAlign(12)
statsPFMET.SetFillColor(0)
statsPFMET.SetLineColor(kGreen+2)
statsPFMET.SetTextColor(kGreen+2)
h_PFMET.GetListOfFunctions().Add(statsPFMET)

canvas = TCanvas("c","",800,800)

h_GenMET.Draw()
h_CaloMET.Draw("sames")
h_TCMET.Draw("sames")
h_PFMET.Draw("sames")

legend = TLegend(0.75,0.55,1.0,0.8)
legend.SetBorderSize(1)
legend.SetFillColor(0)
legend.AddEntry(h_GenMET,"GenMETTrue","l")
legend.AddEntry(h_CaloMET,"CaloMET","l")
legend.AddEntry(h_TCMET,"TCMET","l")
legend.AddEntry(h_PFMET,"PFMET","l")
legend.Draw()

canvas.SaveAs("MET_RECOAOD.png")
canvas.SetLogy()
canvas.SaveAs("MET_RECOAOD_log.png")
